---
#Плагин написал Forter
#если нужна помощь пишите: vk.com\mrforter
ServerName: "<Название сервера>"

#частота обновление в тиках(20 тиков = 1 секунда)
updata: 10

#миры в котором будет работать хот-бар
#пример
#- "world"
#- "nether"
#- "ender"
Default-world:
 - "world"

#Формат текста:
# Tip 
# Popup
Format-Send: "Tip"

#обозначение когда игрок без клана
Default-faction: "Без клана"

#формат времени
#{год} - какой год
#{месяц} - какой месяц
#{день} - какой день
#{час} - какой час
#{минут} - сколько минут
#{секунд} - сколько секунд
FormatData: "{год}/{месяц}/{день} {час}:{минут}({секунд})"
#формат месяца
#месяц - показывает месяц в словах
#число - показывает месяц в числах
monthFormat: "число"

#дистанция поиска игрока в блоках
distance-near: 50

#{ServerName} - показывает название сервера
#{data} - показывает дату в реальной жизни
#{nick} - показывает имя игрока
#{clan} - показывает клан игрока
#{item} - показывает имя предмета в руке
#{IDitem} - показывает айди предмета в руке
#{DAMAGitem} - показывает датy предмета в руке
#{money} - показывает баланс игрока
#{group} - показывает привилегия игрока
#{x}, {y}, {z} - показывает координаты игрока
#{color} - показывает радужный цвет
#{right} - показывает сместить хот-бар в вправо
#{online} - показывает онлайн на сервере
#{maxOnline} - показывает предельный онлайн на сервере
#{tps} - показывает тпс сервера
#{ping} - показывает пинг сервера
#{near} - поиск игроков на сервере

HotBar: 
 - "{right}{color}------------------------"
 - "{right}{color}|§r сервер: {color}{ServerName}"
 - "{right}{color}|§r пинг: {ping}"
 - "{right}{color}|§r дата: {data}"
 - "{right}{color}|§r ник: {nick}"
 - "{right}{color}|§r клан: {clan}"
 - "{right}{color}|§r предмет: {item}({IDitem}, {DAMAGitem})"
 - "{right}{color}|§r баланс: {money}"
 - "{right}{color}|§r привилегия: {group}"
 - "{right}{color}|§r {x}, {y}, {z}"
 - "{right}{color}|§r {online}/{maxOnline}"
 - "{right}{color}|§r TPS: {tps}"
 - "{right}{color}|§r near: {near}"
 - "{right}{color}------------------------"
...